### ISSUE TITLE
OLS down?

### ISSUE THREAD

**Issue by lcdaugherty** [EBISPOT/ols4#742] opened 2024-09-18 09:11 UTC
![Screenshot 2024-09-18 100408](https://github.com/user-attachments/assets/1181ae72-6996-4f5e-bed0-e35cfc43b8b4)
![Screenshot 2024-09-18 100355](https://github.com/user-attachments/assets/acb912f9-8992-47fa-8f97-2baa246c6d6e)
![Screenshot 2024-09-18 100148](https://github.com/user-attachments/assets/802fe76c-07a6-445c-8f4e-d3d115c6d3fd)
![Screenshot 2024-09-18 100031](https://github.com/user-attachments/assets/e47bc31a-dd2d-454a-bdd2-a6cda6466788)
![Screenshot 2024-09-18 095731](https://github.com/user-attachments/assets/f5628d0e-5168-4312-ade9-c8fccad82b85)

**Comment by haideriqbal** [comment] 2024-09-18 09:22
We are aware and working on resolving it. Thanks for reporting

**Comment by lcdaugherty** [comment] 2024-09-18 09:33
Thank you.
I feel like I am jinxing OLS, as whenever I need to do some dedicated work using it, It breaks! :)
Hope you can resolve the issue but in the meantime I can do something else!

**Comment by haideriqbal** [comment] 2024-09-18 09:41
haha its not you... we are facing issues with our kubernetes cluster since yesterday... so fixing that

**Comment by MateuszDev96** [comment] 2024-09-18 09:54
OK, I'm almost sure that after my query the server is not working :) Spacing between my queries on swagger was about 3sec

**Comment by haideriqbal** [comment] 2024-09-18 10:15
OLS is up now! but it is brittle atm... i'm still finding the root cause of why our backend pods keep coming down... will keep you guys posted.

**Comment by haideriqbal** [comment] 2024-09-23 10:11
We had issues with our Neo4J pod because of which our readiness probe was failing and hence OLS coming down... it has been sorted now and we have allocated more resources to our Neo4J pod.

**Closed as completed by haideriqbal** 2024-09-23 10:11 UTC
Labels: production outage
