### ISSUE TITLE
ontology snomed ct - {E201} Multiple children of property element

### ISSUE THREAD

**Issue by deepananbu** [EBISPOT/ols4#676] opened 2024-06-12 12:56 UTC
Hi,
While loading the ontology "**snomed ct"** through ols4, we are getting the error **"{E201} Multiple children of property element"**. But, we could see that it was loaded in OLS search. Is there any changes need to be done before loading this ontology?

Please share the steps if any and let me know if any other information required.

**Comment by henrietteharmse** [comment] 2024-06-12 13:04
We have a version of Snomed from 2020 which is most likely is much older than the version you have.
I suspect it is due to these differences. We did not do anything special to load it.

**Comment by henrietteharmse** [comment] 2024-06-12 13:05
If you can give us a minimal complete subset of Snomed that reproduces the problem, we can have look at it.

**Comment by deepananbu** [comment] 2024-06-12 13:36
These are IRI information we have in ontology file. Hope this helps
http://snomed.info/sct/900000000000207008>
http://snomed.info/sct/900000000000207008/version/20220427>

**Comment by henrietteharmse** [comment] 2024-06-12 13:39
That does not help. We need a minimal complete snomed rdf/xml file that reproduces the error you get.

**Comment by henrietteharmse** [comment] 2024-06-21 10:28
@deepananbu Do you have minimal reproducible example for us? Or can we close this ticket?

**Comment by deepananbu** [comment] 2024-06-21 10:35
@henrietteharmse  I don't have an example currently. Please close the ticket for now

**Closed as completed** 2024-06-21 10:38 UTC
Labels: bug
