### ISSUE TITLE
Every other Search query on the Ontologies page does not return correct results

### ISSUE THREAD

**Issue by twhetzel** [EBISPOT/ols4#536] opened 2023-10-05 15:49 UTC
**Describe the bug**
When I go to the "Ontologies" page and search for an ontology by abbreviation, every other search result is incorrect and only shows the full list of ontologies.

**To Reproduce**
- go to https://www.ebi.ac.uk/ols4/ontologies?search
- search for an ontology, e.g. mondo
- the first search only shows all of the ontologies
- clicking in the search box again does not trigger another search
- deleting the last character from the ontology name search string, e.g. mond, does trigger a new search and then filters the ontology list correctly
- trying another search repeats the steps above

**Expected behavior**
The ontology list should be filtered on the first search

**Comment by serjoshua** [comment] 2023-10-06 09:58
This is caused by a lag on the first few queries' search results. Since it searches everytime you type a letter, the first letter will always trigger an API call that will return many results; second letter, many but lesser than the first one; etc.

This is definitely a performance issue that could be addressed in multiple ways: restricting search results, modifying search, etc. We appreciate you raising this issue.

**Comment by haideriqbal** [comment] 2024-07-04 12:48
The issue has been fixed in production now.

**Closed as completed by haideriqbal** 2024-07-04 12:48 UTC
Labels: bug, low priority
