### ISSUE TITLE
OLS4 cannot load any data without being down (possible Error 500)

### ISSUE THREAD

**Issue by cpauvert** [EBISPOT/ols4#520] opened 2023-09-23 10:24 UTC
**Describe the bug**
Hi, thanks for maintaining the OLS4!
The server might be down as any search (since an hour an a half) returns 0 results, no autocompletion is available and the data content panel does not load.

**To Reproduce**
1. Go to https://www.ebi.ac.uk/ols4
2. See the absence of data load error
3. Type 'leaf' and Enter
4. See error of 0 results

The server seems to be down (possible error 500)

**Expected behavior**
- The usual data content panel with OLS4 statistics
- List of terms for the leaf requests

**Screenshots**

Interface without data load

![image](https://github.com/EBISPOT/ols4/assets/12406679/cbf6a945-c61d-44b1-b578-f279392140ae)

Using the Web Inspector of Firefox indicates that this could be error 500 (in pink on the right)

![Screenshot_2023-09-23_12-19-20](https://github.com/EBISPOT/ols4/assets/12406679/de7e3bf0-b032-4ec6-93e8-0c92adc65700)

**Additional context**
Tested on Firefox 117.0 Ubuntu and Brave Browser 1.57.57 Chromium: 116.0.5845.163 (Official Build) (64-bit)

**Comment by emquardokus** [comment] 2023-09-23 14:53
+1 for problem; it's not loading any ontologies currently for me either.

**Comment by henrietteharmse** [comment] 2023-09-26 08:13
I have investigated this and none of the pods on Kubernetes came down during this time nor has any of the resource limits been hit. In following up with our infrastructure team they said 1 of the worker nodes were experiencing issues and that it is now fixed. However, usually when that happens the related pods will restart or there at least will be a spike in resource usage. There was no restart of any pods during this period of time nor any resource use spikes. Infrastructure have not given any feedback as to what they fixed or how it can be prevented from happening again. I am still following up with them to try and get answers.

I am monitoring this as best as I can. 

Thank you for reporting this. I really appreciate it if for no other reason than to create a record of the resource/infrastructure issues that OLS is experiencing.

**Comment by cpauvert** [comment] 2023-09-26 08:25
Thanks @henrietteharmse  for looking into this! Should I close the issue or you prefer to leave it open to document new insights?
Best,

**Comment by henrietteharmse** [comment] 2023-09-26 08:29
Lets leave it open for now. Hopefully I can get more info from infrastructure and give feedback as to why this happened.

**Comment by henrietteharmse** [comment] 2023-09-26 14:32
Infrastructure came back and said it is due to some request and limit configurations on the Kubernetes cluster (i.e., monitoring in particular) itself being inadequate. They will make these changes as soon as they can, but this will probably be only in next week due to staffing constraints.

**Comment by henrietteharmse** [comment] 2023-10-03 13:50
I can confirm this change has now been applied by infrastructure, which addresses this issue.

**Closed as completed by henrietteharmse** 2023-10-03 13:50 UTC
Labels: production outage
